" Autor: Robson Vaamonde
" Site: www.procedimentosemti.com.br
" Facebook: facebook.com/ProcedimentosEmTI
" Facebook: facebook.com/BoraParaPratica
" YouTube: youtube.com/BoraParaPratica
" Linkedin: https://www.linkedin.com/in/robson-vaamonde-0b029028/
" Instagram: https://www.instagram.com/procedimentoem/?hl=pt-br
" Data de criação: 12/02/2022
" Data de atualização: 12/02/2022
" Versão: 0.01
" Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
" Testado e homologado para a versão do VIM v8.x
"
" Configurações Globais do Editor de Texto VIM
"
" Todos os padrões de todo o sistema são definidos em $VIMRUNTIME/debian.vim 
" e originados pela chamada de: runtime
runtime! debian.vim
"
" O Vim carregará $VIMRUNTIME/defaults.vim se o usuário não tiver um vimrc.
" let g:skip_defaults_vim = 1
"
" Descomente a próxima linha para tornar o Vim mais compatível com o Vi
"set compatible
"
" Vim5 e versões posteriores suportam realce de sintaxe. Descomentando a 
" linha abaixo será habilitado o realce de sintaxe por padrão. 
if has("syntax")
  syntax on
endif
"
" Se estiver usando um fundo escuro na área de edição e realce de sintaxe
" ative esta opção também 
"set background=dark
"
" Descomente o seguinte para que o Vim pule para a última posição quando
" reabrindo um arquivo 
"au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"
" Descomente a linha abaixo para que o Vim carregue as regras e plugins de 
" recuo de acordo com o tipo de arquivo detectado.
"filetype plugin indent on
"
" Setando e habilitando os recursos básicos do editor de texto Vim
"set showcmd
"set showmatch
"set ignorecase	
"set smartcase
"set incsearch
"set autowrite
"set hidden
"set mouse=a
set number
"
"Origem de um arquivo de configuração global, se disponível
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif
